version: '3.8'

services:
  api:
    build: 
      context: ./microservice-flask   
      dockerfile: Dockerfile   
    ports:
      - "5000:5000"   
    environment:
      - FLASK_ENV=development  
    volumes:
      - ./microservice-flask:/api   
    networks:
      - ImageDatabase   
 
  
  web:
    build:
      context: ./microservice-front
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    networks:
      - ImageDatabase
    
 
networks:
  ImageDatabase:  # Define a rede